name: Copy and Zip YAML Files

on:
  push:
    paths:
      - 'Ordner1/Test1/UCID1/ucid1.yml'
      - 'Ordner1/Test1/UCID1/ucid2.yml'
      - 'Ordner1/Test1/UCID1/ucid3.yml'

jobs:
  copy_and_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ATOMIC directory
      run: mkdir -p ATOMIC

    - name: Copy YAML files to ATOMIC directory
      run: |
        cp Ordner1/Test1/UCID1/ucid1.yml ATOMIC/
        cp Ordner1/Test1/UCID1/ucid2.yml ATOMIC/
        cp Ordner1/Test1/UCID1/ucid3.yml ATOMIC/

    - name: Zip the ATOMIC directory
      run: zip -r ATOMIC.zip ATOMIC

    - name: List files in ATOMIC.zip
      run: unzip -l ATOMIC.zip