name: copy_files

on:
  push:
    paths:
      - 'Ordner1/Test1/UCID1/ucid1.yml'
      - 'Ordner1/Test1/UCID2/ucid2.yml'
      - 'Ordner1/Test1/UCID3/ucid3.yml'

jobs:
  copy_and_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: Create ATOMIC directory
      run: |
        mkdir -p ATOMIC
        mkdir -p Ordner1/ATOMIC
        mkdir -p /home/runner/work/CO-sec/CO-sec/ATOMIC

    - name: Copy YAML files to ATOMIC directory
      run: |
        cp Ordner1/Test1/UCID1/ucid1.yml ATOMIC/
        cp Ordner1/Test1/UCID2/ucid2.yml ATOMIC/
        cp Ordner1/Test1/UCID3/ucid3.yml ATOMIC/

    - name: Verify ATOMIC directory creation and contents
      run: ls -l ATOMIC

    - name: Zip the ATOMIC directory
      run: zip -r ATOMIC.zip ATOMIC

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ATOMIC.zip
        git commit -m "Add zipped ATOMIC directory"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}