name: Copy Files on Change

on:
  push:
    paths:
      - 'Ordner1\Test1\UCID1\ucid1.yml'
      - 'Ordner1\Test1\UCID1\ucid2.yml'

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create backup directory
      run: mkdir -p backup

    - name: Copy files to backup directory
      run: |
        cp -r src backup/
        cp -r config backup/

    - name: List files in backup directory
      run: ls -R backup
