name: create_dir

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create directories
        run: mkdir -p myNewFolder/myNewSubFolder

      - name: List contents of myNewSubFolder
        run: ls myNewFolder/myNewSubFolder